### ISSUE TITLE
Bot replies are in a downloadable file called "files" - MatterMost

### ISSUE THREAD

**Issue by waydh** [nautobot/nautobot-app-chatops#312]
### Environment
* Python version:  3.9.18
* Nautobot version:  2.2.0
* nautobot-chatops version:  3.0.2
* MatterMost version: 9.6.1
![nautobot-chat-ops](https://github.com/nautobot/nautobot-app-chatops/assets/74520004/1b51a99a-b5e2-4a88-8fd4-efe104fb21be)

### Expected Behavior
Bot to reply in a text message, not with the text in a downloadable file called "files".

### Observed Behavior
All bot responses are in a downloadable file called "files"

### Steps to Reproduce
1. Issue slash command
2. Bot responds with a downloadable file called "files" which contains the text of the response.
3. See the screenshot for more details.

**Comment by smk4664** [comment]
This is due to Mattermost limitations in message response. Any table is uploaded as a snippet. This is the same with Slack, but small snippets in Slack are automatically rendered by Slack.

**Comment by waydh** [comment]
Thank you for your reply. That's unfortunate.

**Comment by smk4664** [comment]
We already support other methods, such as `send_markdown`. But many of the built-in commands such as `get-devices` were built using `send_large_table` which uses snippets.
